import conn.plasmaCon;
import java.awt.Color;
import java.awt.Label;
import java.awt.TextField;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Miti
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    plasmaCon p;
    SendEmail sm = new SendEmail();
    int randomNum;
    
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHead = new javax.swing.JLabel();
        panChange = new javax.swing.JPanel();
        panOld = new javax.swing.JPanel();
        lblCemail = new javax.swing.JLabel();
        txtCmail = new javax.swing.JTextField();
        txtCpass = new javax.swing.JPasswordField();
        lblCpass = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        lblError1 = new javax.swing.JLabel();
        panNew = new javax.swing.JPanel();
        lblError2 = new javax.swing.JLabel();
        lblNemail = new javax.swing.JLabel();
        txtNmail = new javax.swing.JTextField();
        lblNpass = new javax.swing.JLabel();
        txtNpass = new javax.swing.JPasswordField();
        lblError3 = new javax.swing.JLabel();
        lblCmpass = new javax.swing.JLabel();
        txtCmpass = new javax.swing.JPasswordField();
        btnSendotp = new javax.swing.JButton();
        lblOtp = new javax.swing.JLabel();
        txtOtp = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnResendotp = new javax.swing.JButton();
        lblError4 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHead.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblHead.setForeground(new java.awt.Color(0, 204, 0));
        lblHead.setText("Admin");
        getContentPane().add(lblHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 120, 50));

        panChange.setBorder(javax.swing.BorderFactory.createTitledBorder("Change Settings"));

        panOld.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Old Details"));

        lblCemail.setText("Enter Current Email-Id");

        txtCmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmailActionPerformed(evt);
            }
        });
        txtCmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCmailFocusLost(evt);
            }
        });

        txtCpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpassActionPerformed(evt);
            }
        });

        lblCpass.setText("Password");

        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        lblError1.setForeground(new java.awt.Color(255, 0, 0));
        lblError1.setText("Please fill all details..!");

        javax.swing.GroupLayout panOldLayout = new javax.swing.GroupLayout(panOld);
        panOld.setLayout(panOldLayout);
        panOldLayout.setHorizontalGroup(
            panOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOldLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panOldLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panOldLayout.createSequentialGroup()
                        .addGroup(panOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCemail, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCpass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblError1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCpass)
                            .addComponent(txtCmail, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panOldLayout.setVerticalGroup(
            panOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOldLayout.createSequentialGroup()
                .addComponent(lblError1)
                .addGap(18, 18, 18)
                .addGroup(panOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCemail))
                .addGap(18, 18, 18)
                .addGroup(panOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpass)
                    .addComponent(txtCpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnContinue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panNew.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter New Details"));

        lblError2.setForeground(new java.awt.Color(255, 0, 0));
        lblError2.setText("Please fill all details..!");

        lblNemail.setText("New Email-Id");

        txtNmail.setEnabled(false);
        txtNmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNmailActionPerformed(evt);
            }
        });
        txtNmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNmailFocusLost(evt);
            }
        });

        lblNpass.setText("Password");

        txtNpass.setEnabled(false);
        txtNpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNpassFocusLost(evt);
            }
        });
        txtNpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNpassKeyReleased(evt);
            }
        });

        lblError3.setForeground(new java.awt.Color(255, 0, 0));

        lblCmpass.setText("Confirm Password");

        txtCmpass.setEnabled(false);
        txtCmpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCmpassFocusLost(evt);
            }
        });

        btnSendotp.setText("Send OTP");
        btnSendotp.setEnabled(false);
        btnSendotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendotpActionPerformed(evt);
            }
        });

        lblOtp.setText("Enter OTP");

        txtOtp.setEnabled(false);

        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnResendotp.setText("Re-send OTP");
        btnResendotp.setEnabled(false);
        btnResendotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResendotpActionPerformed(evt);
            }
        });

        lblError4.setForeground(new java.awt.Color(255, 0, 0));
        lblError4.setText("Password does not match");

        javax.swing.GroupLayout panNewLayout = new javax.swing.GroupLayout(panNew);
        panNew.setLayout(panNewLayout);
        panNewLayout.setHorizontalGroup(
            panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNewLayout.createSequentialGroup()
                .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panNewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panNewLayout.createSequentialGroup()
                                .addComponent(lblCmpass)
                                .addGap(18, 18, 18)
                                .addComponent(txtCmpass, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblError4))
                            .addGroup(panNewLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panNewLayout.createSequentialGroup()
                                .addComponent(lblOtp)
                                .addGap(60, 60, 60)
                                .addComponent(txtOtp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnResendotp))
                            .addGroup(panNewLayout.createSequentialGroup()
                                .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panNewLayout.createSequentialGroup()
                                        .addComponent(lblNemail)
                                        .addGap(47, 47, 47))
                                    .addGroup(panNewLayout.createSequentialGroup()
                                        .addComponent(lblNpass)
                                        .addGap(63, 63, 63)))
                                .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panNewLayout.createSequentialGroup()
                                        .addComponent(txtNpass, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblError3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNmail, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblError2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panNewLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnSendotp, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panNewLayout.setVerticalGroup(
            panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panNewLayout.createSequentialGroup()
                .addComponent(lblError2)
                .addGap(18, 18, 18)
                .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNemail)
                    .addComponent(txtNmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNpass)
                    .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblError3)))
                .addGap(18, 18, 18)
                .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCmpass)
                    .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCmpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblError4)))
                .addGap(18, 18, 18)
                .addComponent(btnSendotp)
                .addGap(23, 23, 23)
                .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOtp)
                    .addComponent(btnResendotp))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panChangeLayout = new javax.swing.GroupLayout(panChange);
        panChange.setLayout(panChangeLayout);
        panChangeLayout.setHorizontalGroup(
            panChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panChangeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panOld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panChangeLayout.setVerticalGroup(
            panChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panChangeLayout.createSequentialGroup()
                .addComponent(panOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(panNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        getContentPane().add(panChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 550, 610));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1245, 20, 80, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plasma1.jpg"))); // NOI18N
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1360, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCmailFocusLost
        
        email(txtCmail, lblError1);
    }//GEN-LAST:event_txtCmailFocusLost

    public void errorBlank(JLabel jl)
    {
        jl.setText("");
    }
    
    private void btnSendotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendotpActionPerformed

        String s1 = "", s2 = "", s3 = "";
        
        s1 = txtNmail.getText();
        s2 = txtNpass.getText();
        s3 = txtCmpass.getText();
        
        if(!s1.equals("") && !s2.equals("") && !s3.equals(""))
        {
            errorBlank(lblError2);
            try {
                randomNum = sm.sendEmail(s1);
            } catch (SQLException ex) {
//                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtNmail.setEnabled(false);
            txtNpass.setEnabled(false);
            txtCmpass.setEnabled(false);
            btnSendotp.setEnabled(false);
            txtOtp.setEnabled(true);
            btnResendotp.setEnabled(true);
            btnUpdate.setEnabled(true);
            
        }
        else
        {
            lblError2.setVisible(true);
            lblError2.setText("Please fill all details...");
        }
    }//GEN-LAST:event_btnSendotpActionPerformed

    private void txtNmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNmailActionPerformed

    private void txtNmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNmailFocusLost

        email(txtNmail, lblError2);

    }//GEN-LAST:event_txtNmailFocusLost

    public void clear()
    {
        txtCmail.setText("");
        txtCpass.setText("");
        txtNmail.setText("");
        txtNpass.setText("");
        txtCmpass.setText("");
        txtOtp.setText("");
    }
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        String update = "", otp = "", s1 = "", s2 = "";
        otp = txtOtp.getText();
        s1 = txtNmail.getText();
        s2 = txtNpass.getText();

        if(!otp.equals(""))
        {
            errorBlank(lblError2);
            
            try
            {
                p = new plasmaCon();
                p.st = p.con.createStatement();
                update = "update tbl_admin set email = '"+s1+"', emailpass = '"+s2+"'";
                p.st.executeUpdate(update);
                JOptionPane.showMessageDialog(null, "Admin Details Updated...");
                clear();
                txtCmail.setEnabled(true);
                txtCpass.setEnabled(true);
                btnContinue.setEnabled(true);
                txtOtp.setEnabled(false);
                btnResendotp.setEnabled(false);
                btnUpdate.setEnabled(false);
            }catch(Exception e){}
        }
        else
        {
            txtOtp.setBackground(Color.GRAY);
            txtOtp.requestFocus();
//            lblError5.setText("Please enter OTP...");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResendotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResendotpActionPerformed
        
        String s1 = txtNmail.getText();
        try {
            randomNum = sm.sendEmail(s1);
        }catch(Exception e){}
    }//GEN-LAST:event_btnResendotpActionPerformed

    private void txtNpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNpassFocusLost

        int i = txtNpass.getText().length();

        if(i<=6)
        {
            txtNpass.requestFocus();
        }
        else
        {
            errorBlank(lblError3);
        }
    }//GEN-LAST:event_txtNpassFocusLost

    private void txtNpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNpassKeyReleased

        lblError1.setVisible(true);
        String s = txtNpass.getText();
        if(s.length() <= 6)
        {
            lblError3.setText("Weak Password..!");
            lblError3.setForeground(Color.red);
        }
        else
        {
            lblError3.setText("Strong Password..!");
            lblError3.setForeground(Color.GREEN);
        }        
    }//GEN-LAST:event_txtNpassKeyReleased

    private void txtCmpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCmpassFocusLost
        
        String pass = null, cpass = null;
        pass = txtNpass.getText();
        cpass = txtCmpass.getText();
        
        if(cpass.equals(""))
        {
            errorBlank(lblError4);
        }
        else if(!pass.equals(cpass))
        {
            lblError4.setVisible(true);
            lblError4.setText("Password Does not match...");
            txtNpass.requestFocus();
        }
        else
        {
            lblError2.setVisible(false);
        }
    }//GEN-LAST:event_txtCmpassFocusLost

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed

                //        errorBlank(lblError1);
//        JOptionPane.showMessageDialog(null, "btn start...");

        String s1 = "", s2 = "", ss1 = "", ss2 = "", select;
        s1 = txtCmail.getText();
        s2 = txtCpass.getText();

        if(!s1.equals("") && !s2.equals(""))
        {
            JOptionPane.showMessageDialog(null, "if start...");
            errorBlank(lblError1);
            try
            {
                JOptionPane.showMessageDialog(null, "try start...");
                p = new plasmaCon();
                p.st = p.con.createStatement();
                select = "select email,emailpass from tbl_admin";
                p.rs = p.st.executeQuery(select);

                while(p.rs.next())
                {
                    ss1 = p.rs.getString("email");
                    ss2 = p.rs.getString("emailpass");
                }

                if(s1.equals(ss1) && s2.equals(ss2))
                {
                    JOptionPane.showMessageDialog(null, "inner if start...");
                    errorBlank(lblError1);
                    txtNmail.setEnabled(true);
                    txtNpass.setEnabled(true);
                    txtCmpass.setEnabled(true);
                    btnSendotp.setEnabled(true);
                    txtCmail.setEnabled(false);
                    txtCpass.setEnabled(false);
                    btnContinue.setEnabled(false);
                }
                else
                {
                    lblError1.setText("Enter Correct Details...");
                }
                p.rs.close();
                p.con.close();

            }catch(Exception e){}

        }
        else
        {
            lblError1.setVisible(true);
            lblError1.setText("Please fill all details...");
            JOptionPane.showMessageDialog(null, "else start...");
        }
    }//GEN-LAST:event_btnContinueActionPerformed

    private void txtCpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpassActionPerformed

    private void txtCmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCmailActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        lblError1.setVisible(false);
        lblError2.setVisible(false);
        lblError4.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        dispose();
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void email(JTextField txtfield, JLabel errorlbl)
    {
        String z = txtfield.getText();
        errorlbl.setVisible(false);
        
        if(!z.equals(""))
        {
            if(!(((z.contains("gmail.com"))|| (z.contains("yahoo.com")) || (z.contains("yahoo.co.in"))|| (z.contains("gmail.co.in"))) && z.contains("@")))
            {
                errorlbl.setVisible(true);
                errorlbl.setText("Please insert correct email-id..!");
                errorlbl.setForeground(Color.red);
                txtfield.requestFocus();
                txtfield.setBackground(Color.LIGHT_GRAY);
            }
            else
            {
                errorlbl.setText("");
                txtfield.setBackground(Color.white);
            }
        }
        
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnResendotp;
    private javax.swing.JButton btnSendotp;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblCemail;
    private javax.swing.JLabel lblCmpass;
    private javax.swing.JLabel lblCpass;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblError2;
    private javax.swing.JLabel lblError3;
    private javax.swing.JLabel lblError4;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblNemail;
    private javax.swing.JLabel lblNpass;
    private javax.swing.JLabel lblOtp;
    private javax.swing.JPanel panChange;
    private javax.swing.JPanel panNew;
    private javax.swing.JPanel panOld;
    private javax.swing.JTextField txtCmail;
    private javax.swing.JPasswordField txtCmpass;
    private javax.swing.JPasswordField txtCpass;
    private javax.swing.JTextField txtNmail;
    private javax.swing.JPasswordField txtNpass;
    private javax.swing.JTextField txtOtp;
    // End of variables declaration//GEN-END:variables
}
