import conn.plasmaCon;
import conn.plasmaCon;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prital
 */
public class ChangePassword extends javax.swing.JFrame {

    
    /**
     * Creates new form ChangePassword
     */
    plasmaCon c;
    String LoginId;
    
    public ChangePassword() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        lblMain = new javax.swing.JLabel();
        panOld = new javax.swing.JPanel();
        lblOld = new javax.swing.JLabel();
        txtOpass = new javax.swing.JPasswordField();
        btnContinue = new javax.swing.JButton();
        lblErrorMain = new javax.swing.JLabel();
        panNew = new javax.swing.JPanel();
        lblNew = new javax.swing.JLabel();
        lblCpass = new javax.swing.JLabel();
        txtNpass = new javax.swing.JPasswordField();
        txtCpass = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblError2 = new javax.swing.JLabel();
        lblError3 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1364, 699));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMain.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblMain.setForeground(new java.awt.Color(0, 255, 0));
        lblMain.setText("Change Password");
        panMain.add(lblMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        panOld.setBorder(javax.swing.BorderFactory.createTitledBorder("Old Password"));

        lblOld.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblOld.setText("Old Password");

        btnContinue.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        lblErrorMain.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panOldLayout = new javax.swing.GroupLayout(panOld);
        panOld.setLayout(panOldLayout);
        panOldLayout.setHorizontalGroup(
            panOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOldLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panOldLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(panOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblErrorMain, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panOldLayout.createSequentialGroup()
                        .addComponent(lblOld)
                        .addGap(18, 18, 18)
                        .addComponent(txtOpass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
        );
        panOldLayout.setVerticalGroup(
            panOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOldLayout.createSequentialGroup()
                .addComponent(lblErrorMain, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOld)
                    .addComponent(txtOpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnContinue)
                .addContainerGap())
        );

        panMain.add(panOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 492, 140));

        panNew.setBorder(javax.swing.BorderFactory.createTitledBorder("New Password"));

        lblNew.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblNew.setText("New Password");

        lblCpass.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblCpass.setText("Confirm Password");

        txtNpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNpassFocusLost(evt);
            }
        });
        txtNpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNpassKeyReleased(evt);
            }
        });

        txtCpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpassFocusLost(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnSubmit.setText("Update");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnCancel.setText("Clear");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblError3.setForeground(new java.awt.Color(255, 0, 0));
        lblError3.setText("Password does not match..!");

        javax.swing.GroupLayout panNewLayout = new javax.swing.GroupLayout(panNew);
        panNew.setLayout(panNewLayout);
        panNewLayout.setHorizontalGroup(
            panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNewLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panNewLayout.createSequentialGroup()
                        .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCpass)
                            .addComponent(lblNew))
                        .addGap(18, 18, 18)
                        .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNpass, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblError3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCpass, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(lblError2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panNewLayout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))))
        );
        panNewLayout.setVerticalGroup(
            panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNewLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNew)
                    .addComponent(txtNpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError2)
                .addGap(26, 26, 26)
                .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpass)
                    .addComponent(txtCpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lblError3)
                .addGap(27, 27, 27)
                .addGroup(panNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panMain.add(panNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, 230));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plasma1.jpg"))); // NOI18N
        panMain.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -5, 1370, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed

    lblErrorMain.setVisible(false);
    c = new plasmaCon();
    int i = Integer.parseInt(LoginId);
    String select = "", dbpass = "";
    String oldpass =  txtOpass.getText();
    int count = 0;
    
        try
        {
            if(!oldpass.equals(""))
            {
                c.st = c.con.createStatement();
                select = "select password from tbl_register where rid = "+i+"";
    //            JOptionPane.showMessageDialog(null, "Query Write...");
                c.rs = c.st.executeQuery(select);
    //            JOptionPane.showMessageDialog(null, "Query Excecute...");

                while(c.rs.next())
                {
                    dbpass = c.rs.getString("password");
                    if(oldpass.equals(dbpass))
                    {
                        panNew.setVisible(true);
                        panOld.setVisible(false);
                        count++;
                    }
                }
                if(count == 0)
                {
                    lblErrorMain.setVisible(true);
                    lblErrorMain.setText("Password Incorrct...");
                }

                c.con.close();
                
            }
            else
            {
                lblErrorMain.setVisible(true);
                lblErrorMain.setText("Please insert old password...");
//                JOptionPane.showMessageDialog(null, "Please insert old password...");
            }
        
        }catch(Exception e){}
    }//GEN-LAST:event_btnContinueActionPerformed

    private void txtNpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNpassFocusLost

        String npass = txtNpass.getText();
        int i = npass.length();
        lblError2.setVisible(false);
        
        if(!npass.equals(""))
        {
            if(i<=6)
            {
                txtNpass.requestFocus();
            }
            else
            {
                lblError2.setVisible(false);
            }                    
        }


    }//GEN-LAST:event_txtNpassFocusLost

    private void txtNpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNpassKeyReleased

        lblError2.setVisible(true);
        String s = txtNpass.getText();
        if(s.length() <= 6)
        {
            lblError2.setText("Weak Password...");
            lblError2.setForeground(Color.red);
        }
        else
        {
            lblError2.setText("Strong Password...");
            lblError2.setForeground(Color.GREEN);
        }        
    }//GEN-LAST:event_txtNpassKeyReleased

    private void txtCpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpassFocusLost

        String pass = null, cpass = null;
        pass = txtNpass.getText();
        cpass = txtCpass.getText();
        
        if(cpass.equals(""))
        {
            lblError3.setVisible(false);
        }
        else if(!pass.equals(cpass))
        {
            lblError3.setVisible(true);
            txtNpass.requestFocus();
        }
        else
        {
            lblError3.setVisible(false);
        }        
    }//GEN-LAST:event_txtCpassFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        panNew.setVisible(false);
        lblErrorMain.setVisible(false);
        lblError3.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        String npass = txtNpass.getText();
        String cpass = txtCpass.getText();

        String update;
        int i = Integer.parseInt(LoginId);
        
        try
        {
            if((!npass.equals("")) && (!cpass.equals("")))
            {
                if(npass.equals(cpass))
                {
                    c = new plasmaCon();
                    c.st = c.con.createStatement();
                    update = "update tbl_register set password = '"+npass+"' where rid = "+i+"";
                    c.st.executeUpdate(update);

                    JOptionPane.showMessageDialog(null, "Your password Successfully Updated...");

                    dispose();                    
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "please insert all details...");
            }

//            check ck = new check();
//            ck.setVisible(true);
            
        }catch(Exception e){}
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        txtNpass.setText("");
        txtCpass.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblCpass;
    private javax.swing.JLabel lblError2;
    private javax.swing.JLabel lblError3;
    private javax.swing.JLabel lblErrorMain;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblOld;
    private javax.swing.JPanel panMain;
    private javax.swing.JPanel panNew;
    private javax.swing.JPanel panOld;
    private javax.swing.JPasswordField txtCpass;
    private javax.swing.JPasswordField txtNpass;
    private javax.swing.JPasswordField txtOpass;
    // End of variables declaration//GEN-END:variables
}
