
import conn.plasmaCon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prital
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */
    plasmaCon c;
    String[] s = new String[2];
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        panMain = new javax.swing.JPanel();
        txtUname = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblForget = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnForget = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enter.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panMain.setBackground(new java.awt.Color(204, 204, 204));
        panMain.setPreferredSize(new java.awt.Dimension(1306, 695));
        panMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnameActionPerformed(evt);
            }
        });
        panMain.add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 380, 173, -1));
        panMain.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 420, 173, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panMain.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 460, 90, -1));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        panMain.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 560, 90, 20));

        lblHeading.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(0, 255, 0));
        lblHeading.setText("Plasma Experimental Studio");
        panMain.add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 620, 70));

        lblError.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setText("Username Or Password Incorrect");
        panMain.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, 200, 20));

        lblUsername.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("User Name");
        panMain.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(968, 380, 110, 20));

        lblPassword.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        panMain.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 100, 20));

        lblForget.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblForget.setForeground(new java.awt.Color(255, 255, 255));
        lblForget.setText("Forget Password");
        panMain.add(lblForget, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, 100, 20));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New User ??");
        panMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 560, -1, -1));

        btnForget.setText("Forget Password");
        btnForget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgetActionPerformed(evt);
            }
        });
        panMain.add(btnForget, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 523, 140, 20));

        lblImage.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblImage.setForeground(new java.awt.Color(102, 255, 51));
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plasma1.jpg"))); // NOI18N
        panMain.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 700));

        getContentPane().add(panMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        dispose();
        Register h = new Register();
        h.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

    c = new plasmaCon();
    String un="",pass="";
    String select = "";
    int count = 0;
    
    un = txtUname.getText();
    pass = txtPass.getText();
    
    try
    {
//        JOptionPane.showMessageDialog(null, "s0 = "+s[0]+"s1 = "+s[1]);
        if((!un.equals("")) && (!pass.equals("")))
        {
            if(un.equals(s[0]) && pass.equals(s[1]))
            {
                Admin adm = new Admin();
                dispose();
                adm.setVisible(true);
            }
            else
            {
                c.st = c.con.createStatement();
                select = "select rid,fname,uname,password from tbl_register";
        //        JOptionPane.showMessageDialog(null, "Query Write...");
                c.rs = c.st.executeQuery(select);
        //        JOptionPane.showMessageDialog(null, "Query Excecute...");

                while(c.rs.next())
                {
                    String dbrid = "", dbfname = "", dbuser = "", dbpass = "";

                    dbrid = c.rs.getString("rid");
                    dbfname = c.rs.getString("fname");
                    dbuser = c.rs.getString("uname");
                    dbpass = c.rs.getString("password");

                    if(un.equals(dbuser) && pass.equals(dbpass))
                    {
                        count++;//else part is not allowed in loop as if and else both are run for right and wrong record respectively.
                        dispose(); //login page is disposed here 
                        ViewPage ck = new ViewPage();         //                new check(dbuser,dbrid);
                        ck.LoginId = dbrid; 
                        ck.LoginName = dbfname;
                        ck.setVisible(true);
                    }
                }
                
            }
            if(count==0)
            {
                lblError.setVisible(true);
            }
            c.con.close();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter all details...");
        }
    }catch(Exception e){}

    }//GEN-LAST:event_btnLoginActionPerformed

    public String[] admin()
    {
        String select = "", s0 = "", s1 = "";
//        String[] s = new String[2];
        try
        {
            c = new plasmaCon();
            c.st = c.con.createStatement();
            select = "select user,password from tbl_admin";
            c.rs = c.st.executeQuery(select);
            while(c.rs.next())
            {
                s0 = c.rs.getString("user");
                s1 = c.rs.getString("password");
            }
            c.rs.close();
            c.con.close();
        }catch(Exception e){}

        return new String[]{ s0, s1 };
//        return s;
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        s = admin();
        lblError.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnForgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgetActionPerformed

        dispose();
        ForgetPassword fd = new ForgetPassword();
        fd.setVisible(true);
    }//GEN-LAST:event_btnForgetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForget;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblForget;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panMain;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
