
import conn.plasmaCon;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.plaf.synth.ColorType;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prital
 */
public class Register extends javax.swing.JFrame {
    plasmaCon c;
    SendEmail sm = new SendEmail();
    int randomNum = 0;
    String MyEmail = "", fn = "", ln = "", contact = "";
    
    /**
     * Creates new form HomePage
     */
    public Register() {
        initComponents();

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panInfo = new javax.swing.JPanel();
        lblFname = new javax.swing.JLabel();
        lblLname = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        lblError3 = new javax.swing.JLabel();
        btnTp = new javax.swing.JButton();
        btnSendotp = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        txtOtp = new javax.swing.JTextField();
        lblOtp = new javax.swing.JLabel();
        btnResendotp = new javax.swing.JButton();
        panSecurity = new javax.swing.JPanel();
        lblUname = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblCpass = new javax.swing.JLabel();
        txtCpass = new javax.swing.JPasswordField();
        txtPass = new javax.swing.JPasswordField();
        txtUname = new javax.swing.JTextField();
        lblError2 = new javax.swing.JLabel();
        lblError1 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        panInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFname.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblFname.setText("First Name");
        panInfo.add(lblFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblLname.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblLname.setText("Last Name");
        panInfo.add(lblLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblEmail.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblEmail.setText("E-mail id");
        panInfo.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblContact.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblContact.setText("Contact No.");
        panInfo.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFnameKeyTyped(evt);
            }
        });
        panInfo.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 181, -1));

        txtLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLnameKeyTyped(evt);
            }
        });
        panInfo.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 181, -1));

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        panInfo.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 181, -1));

        txtContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContactFocusLost(evt);
            }
        });
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContactKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactKeyTyped(evt);
            }
        });
        panInfo.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 181, -1));

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        panInfo.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 190, 20));
        panInfo.add(lblError3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 124, 180, 20));

        btnTp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTpActionPerformed(evt);
            }
        });
        panInfo.add(btnTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 100, 0, 20));

        btnSendotp.setText("Send OTP");
        btnSendotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendotpActionPerformed(evt);
            }
        });
        panInfo.add(btnSendotp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        btnContinue.setText("Continue");
        btnContinue.setEnabled(false);
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        panInfo.add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        txtOtp.setEnabled(false);
        panInfo.add(txtOtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 80, -1));

        lblOtp.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblOtp.setText("Enter OTP");
        panInfo.add(lblOtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btnResendotp.setText("Re-send OTP");
        btnResendotp.setEnabled(false);
        btnResendotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResendotpActionPerformed(evt);
            }
        });
        panInfo.add(btnResendotp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jPanel1.add(panInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 350, 300));

        panSecurity.setBorder(javax.swing.BorderFactory.createTitledBorder("Set Up Security"));

        lblUname.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblUname.setText("User Name");

        lblPass.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblPass.setText("Password");

        lblCpass.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        lblCpass.setText("Confirm Password");

        txtCpass.setEnabled(false);
        txtCpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpassFocusLost(evt);
            }
        });

        txtPass.setEnabled(false);
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });

        txtUname.setEnabled(false);

        lblError2.setForeground(new java.awt.Color(255, 0, 0));
        lblError2.setText("Password does not match..!");

        javax.swing.GroupLayout panSecurityLayout = new javax.swing.GroupLayout(panSecurity);
        panSecurity.setLayout(panSecurityLayout);
        panSecurityLayout.setHorizontalGroup(
            panSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSecurityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSecurityLayout.createSequentialGroup()
                        .addComponent(lblCpass)
                        .addGroup(panSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panSecurityLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblError2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panSecurityLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtCpass))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSecurityLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPass)
                            .addComponent(lblUname))
                        .addGap(68, 68, 68)
                        .addGroup(panSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblError1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(txtUname))))
                .addGap(145, 145, 145))
        );
        panSecurityLayout.setVerticalGroup(
            panSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSecurityLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUname)
                    .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lblError1)
                .addGap(18, 18, 18)
                .addGroup(panSecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCpass)
                    .addComponent(txtCpass, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError2)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1.add(panSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 367, 210));

        btnRegister.setText("Register");
        btnRegister.setEnabled(false);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 80, -1));

        btnClear.setText("Clear");
        btnClear.setEnabled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 80, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1257, 20, 90, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plasma1.jpg"))); // NOI18N
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        c = new plasmaCon();        
        String uname = null, pass = null, cpass = null;
        String insert = "";
        
        uname = txtUname.getText();
        pass = txtPass.getText();
        cpass = txtCpass.getText();
//        JOptionPane.showMessageDialog(null, "Fn = "+fn+",  Ln = "+ln+", email = "+email+",  contact = "+contact+",  uname = "+uname+",  pass = "+pass+"");
        try
        {
            
            if(!uname.equals("") && !pass.equals("") && !cpass.equals(""))
            {
                if(pass.equals(cpass))
                {
                  
    //                 JOptionPane.showMessageDialog(null, "Fn = "+fn+",  Ln = "+ln+", email = "+email+",  contact = "+contact+",  uname = "+uname+",  pass = "+pass+"");        
                    c.st = c.con.createStatement();
                    insert = "INSERT into tbl_register (FName,LName,Email_Id,ContactNo,UName,Password) values('"+fn+"','"+ln+"','"+MyEmail+"','"+contact+"','"+uname+"','"+pass+"')";
                    c.st.executeUpdate(insert);
                    JOptionPane.showMessageDialog(null, "You have registered successfully..!");
                    c.con.close();
                    clear();

                    Login l = new Login();
                    dispose();
                    l.setVisible(true);
                    
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Please insert all details..!");
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());}

    }//GEN-LAST:event_btnRegisterActionPerformed

    public void clear()
    {
        txtFname.setText("");
        txtLname.setText("");
        txtEmail.setText("");
        txtContact.setText("");
        txtUname.setText("");
        txtPass.setText("");
        txtCpass.setText("");
    }
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtCpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpassFocusLost

        String pass = null, cpass = null;
        pass = txtPass.getText();
        cpass = txtCpass.getText();
        
        if(cpass.equals(""))
        {
            lblError2.setVisible(false);
        }
        else if(!pass.equals(cpass))
        {
            lblError2.setVisible(true);
            txtPass.requestFocus();
        }
        else
        {
            lblError2.setVisible(false);
        }
    }//GEN-LAST:event_txtCpassFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        lblError2.setVisible(false);
        lblError1.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased

        lblError1.setVisible(true);
        String s = txtPass.getText();
        if(s.length() <= 6)
        {
            lblError1.setText("Weak Password..!");
            lblError1.setForeground(Color.red);
        }
        else
        {
            lblError1.setText("Strong Password..!");
            lblError1.setForeground(Color.GREEN);
        }
    }//GEN-LAST:event_txtPassKeyReleased

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost

        int i = txtPass.getText().length();
        
        if(i<=6)
        {
            txtPass.requestFocus();
        }
        else
        {
            lblError1.setVisible(false);
        }
    }//GEN-LAST:event_txtPassFocusLost

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        
        dispose();
        Login l = new Login();
        l.setVisible(true);        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtCpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpassFocusGained

    }//GEN-LAST:event_txtCpassFocusGained

    private void txtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyTyped

        
        char c = evt.getKeyChar();

        if(txtContact.getText().length()<10)
        {
        
            if(!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE))
            {
                getToolkit().beep();
                evt.consume();
            }
        }
        else
        {
            getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_txtContactKeyTyped

    private void txtContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContactFocusLost

        String contact = txtContact.getText();
        if(!contact.equals(""))
        {
        
            if(contact.length()<10 || contact.length()>10)
            {
                lblError.setVisible(true);
                lblError.setForeground(Color.red);
                lblError.setText("Enter 10 digit number..!");
                txtContact.setBackground(Color.LIGHT_GRAY);
                txtContact.requestFocus();
            }
            else
            {
                lblError.setVisible(false);
                lblError.setText(" ");
                txtContact.setBackground(Color.WHITE);
            }
        }
    }//GEN-LAST:event_txtContactFocusLost

    private void txtContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyPressed

//        char c = evt.getKeyChar();
//        if(txtContact.getText().length()<=10)
//        {
//            getToolkit().beep();
//            evt.consume();
//        }
    }//GEN-LAST:event_txtContactKeyPressed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost

        String z = txtEmail.getText();

        if(!z.equals(""))
        {
            if(!(((z.contains("gmail.com"))|| (z.contains("yahoo.com")) || (z.contains("yahoo.co.in"))|| (z.contains("gmail.co.in"))) && z.contains("@")))
            {
                lblError3.setVisible(true);
                lblError3.setText("Please insert correct email-id..!");
                lblError3.setForeground(Color.red);
                txtEmail.requestFocus();
                txtEmail.setBackground(Color.LIGHT_GRAY);
            }
            else
            {
                lblError3.setText("");
                txtEmail.setBackground(Color.white);
            }
        }

    }//GEN-LAST:event_txtEmailFocusLost


    private void txtFnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyTyped

        char c = evt.getKeyChar();
        if(Character.isDigit(c) || c == KeyEvent.VK_DELETE)
        {
            getToolkit().beep();
            evt.consume();
        }        
        
    }//GEN-LAST:event_txtFnameKeyTyped

    private void txtLnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLnameKeyTyped

        char c = evt.getKeyChar();
        if(Character.isDigit(c) || c == KeyEvent.VK_DELETE)
        {
            getToolkit().beep();
            evt.consume();
        }        

    }//GEN-LAST:event_txtLnameKeyTyped

    private void btnTpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTpActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed

        String s1 = "";
        s1 = txtOtp.getText();
        
        if(!s1.equals(""))
        {
            JOptionPane.showMessageDialog(null, "if start otp = "+randomNum);
            if(s1.equals(String.valueOf(randomNum)))
            {
                JOptionPane.showMessageDialog(null, "if start otp inner");                
                lblError.setText("");
                txtFname.setEnabled(false);
                txtLname.setEnabled(false);
                txtEmail.setEnabled(false);
                txtContact.setEnabled(false);
                txtOtp.setEnabled(false);
                btnContinue.setEnabled(false);
                btnResendotp.setEnabled(false);
                txtUname.setEnabled(true);
                txtPass.setEnabled(true);
                txtCpass.setEnabled(true);
                btnRegister.setEnabled(true);
                btnClear.setEnabled(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Else inner");                
                lblError.setText("Your OTP is incorrecct...");
            }
        }
        else
        {
            lblError.setText("You must enter OTP number...");
        }
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnSendotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendotpActionPerformed

        lblError.setText(" ");
        
        fn = txtFname.getText();
        ln = txtLname.getText();
        contact = txtContact.getText();
        MyEmail = txtEmail.getText();
        
        if(!fn.equals("") && !ln.equals("") && !MyEmail.equals("") && !contact.equals(""))
        {
//            JOptionPane.showMessageDialog(null, "if start");
            sendEmail();
            btnSendotp.setEnabled(false);
            txtOtp.setEnabled(true);
            btnResendotp.setEnabled(true);
            btnContinue.setEnabled(true);
        }
        else
        {
            lblError.setText("You must fill all details...");
        }
    }//GEN-LAST:event_btnSendotpActionPerformed

    public void sendEmail()
    {
        try {
            randomNum = sm.sendEmail(MyEmail);
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnResendotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResendotpActionPerformed

        sendEmail();
    }//GEN-LAST:event_btnResendotpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnResendotp;
    private javax.swing.JButton btnSendotp;
    private javax.swing.JButton btnTp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblCpass;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblError2;
    private javax.swing.JLabel lblError3;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblOtp;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUname;
    private javax.swing.JPanel panInfo;
    private javax.swing.JPanel panSecurity;
    private javax.swing.JTextField txtContact;
    private javax.swing.JPasswordField txtCpass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtOtp;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
