import animatedlinechart.AllTempratureAnimatedLineChart;
import animatedlinechart.TempratureContinuesAnimatedLineChart;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation; 
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.ui.RefineryUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prital
 */
public class ViewPage extends javax.swing.JFrame {

    /**
     * Creates new form check
     */
    String LoginName, LoginId;
    
    public ViewPage() {
        initComponents();

//        cmbmYear();
        //cmbmDate();
    }
    public ViewPage(String s1, String s2) {

        this.LoginId = s1;
        this.LoginName = s2;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnLogout = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        btnLinegraph = new javax.swing.JButton();
        cmbSelect = new javax.swing.JComboBox();
        lblImage = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1680, 1050));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 80, -1));

        lblName.setBackground(new java.awt.Color(102, 102, 102));
        lblName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1162, 10, 70, 30));

        btnLinegraph.setText("Line Graph");
        btnLinegraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinegraphActionPerformed(evt);
            }
        });
        getContentPane().add(btnLinegraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 91, -1));

        cmbSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- - Select Temperature - -" }));
        cmbSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectActionPerformed(evt);
            }
        });
        getContentPane().add(cmbSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 160, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plasma1.jpg"))); // NOI18N
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 690));

        jMenu3.setText("Profile");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Change Password");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Edit Profile");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        menubar.add(jMenu3);

        jMenu1.setText("Observation");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Feedback");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        menubar.add(jMenu1);

        setJMenuBar(menubar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public void cmbDisable()
//    {
//        cmbYear.setVisible(false);
//        cmbMonth.setVisible(false);
//        cmbDate.setVisible(false);
//        cmbHour.setVisible(false);
//        cmbMinute.setVisible(false);
//        cmbSecond.setVisible(false);
//        
//    }
//    

    public void TempComboFill()
    {
        for(int i=0; i<150; i++)
        {
            cmbSelect.addItem(i+1);
        }
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblName.setText(LoginName);
        TempComboFill();
//        cmbDisable();
//        panOption.setVisible(false);
//        panFilter.setVisible(false);
//        btnPie.setVisible(false);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

//        dispose();
        ChangePassword cp = new ChangePassword();
        cp.LoginId = LoginId;
        cp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

//        dispose();
        EditProfile ep = new EditProfile();
        ep.Loginid = LoginId;
        ep.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        dispose();
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLinegraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinegraphActionPerformed
        // TODO add your handling code here:
//        TempratureContinuesAnimatedLineChart tc = new TempratureContinuesAnimatedLineChart();
//        tc.main(null);
        
        String selectTemp = cmbSelect.getSelectedItem().toString();
//        JOptionPane.showMessageDialog(null, "value is "+selectTemp+"");
        
//        new AllTempratureAnimatedLineChart(selectTemp);
    try{
          //  AllTempratureAnimatedLineChart.selectTemp = selectTemp;
        final DynamicLineAndTimeSeriesChart demo = new DynamicLineAndTimeSeriesChart("Dynamic Line And TimeSeries Chart");
        demo.pack();
        RefineryUtilities.centerFrameOnScreen(demo);
        demo.setVisible(true);
           
        }catch(Exception e)
        {
            System.out.println("Error : " + e.getMessage());
        }     
    }//GEN-LAST:event_btnLinegraphActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        Feedback fd = new Feedback();
        fd.LoginId = LoginId;
        fd.LoginName = LoginName;
        fd.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void cmbSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSelectActionPerformed

//    public void mYear()
//    {
//        
//        
//        cmbYear.setVisible(true);
//        cmbMonth.setVisible(false);
//        cmbDate.setVisible(false);
//        cmbHour.setVisible(false);
//        cmbMinute.setVisible(false);
//        cmbSecond.setVisible(false);
//    }
// 
//    public void mMonth()
//    {
//        cmbYear.setVisible(true);
//        cmbMonth.setVisible(true);
//        cmbDate.setVisible(false);
//        cmbHour.setVisible(false);
//        cmbMinute.setVisible(false);
//        cmbSecond.setVisible(false);
//    }
//    
//    public void mDate()
//    {
//        cmbYear.setVisible(true);
//        cmbMonth.setVisible(true);
//        cmbDate.setVisible(true);
//        cmbHour.setVisible(false);
//        cmbMinute.setVisible(false);
//        cmbSecond.setVisible(false);
//    }
//    
//    public void mHour()
//    {
//        cmbYear.setVisible(true);
//        cmbMonth.setVisible(true);
//        cmbDate.setVisible(true);
//        cmbHour.setVisible(true);
//        cmbMinute.setVisible(false);
//        cmbSecond.setVisible(false);
//        
//    }
//    
//    public void mMinute()
//    {
//        cmbYear.setVisible(true);
//        cmbMonth.setVisible(true);
//        cmbDate.setVisible(true);
//        cmbHour.setVisible(true);
//        cmbMinute.setVisible(true);
//        cmbSecond.setVisible(false);
//        
//    }
//    
//    public void mSecond()
//    {
//        cmbYear.setVisible(true);
//        cmbMonth.setVisible(true);
//        cmbDate.setVisible(true);
//        cmbHour.setVisible(true);
//        cmbMinute.setVisible(true);
//        cmbSecond.setVisible(true);
//        
//    }
//    
//    public void cmbmYear()
//    {
//        //int z[] = new int[30];
//        int z1 = 2016;
//        for(int i=0;i<30;i++)
//        {
//            cmbYear.addItem(z1);
//            z1++;
//        }
//    }
//    
//    public void day31()
//    {
//        int z1=1;
//        cmbDate.removeAllItems();
//        for(int i=0;i<31;i++)
//        {
//            cmbDate.addItem(z1);
//            z1++;
//        }        
//    }
//
//    public void day30()
//    {
//        int z1 = 1;
//        cmbDate.removeAllItems();
//        for(int i=0;i<30;i++)
//        {
//            
//            cmbDate.addItem(z1);
//            z1++;
//        }
//    }
//    
//    public void cmbmDate()
//    {
//        JOptionPane.showMessageDialog(null, "cmbDate Start...");
//        int z2;
//        int index = cmbMonth.getSelectedIndex();
//        JOptionPane.showMessageDialog(null, "index = "+index);
//        if(index <=7 && index !=2)
//        {
//            JOptionPane.showMessageDialog(null, "If Start...");
//            if(index / 2 != 0)
//            {
//                JOptionPane.showMessageDialog(null, "day31...");
//                day31();
//            }
//            else if(index == 2)
//            {
//                int inYr = Integer.parseInt(cmbYear.getSelectedItem().toString());
//                if(inYr / 4 != 0)
//                {
//                    z2=1;
//                    cmbDate.removeAllItems();
//                    for(int i=0;i<28;i++)
//                    {
//                        cmbDate.addItem(z2);
//                        z2++;
//                    }
//                }
//                else
//                {
//                    z2=1;
//                    cmbDate.removeAllItems();
//                    for(int i=0;i<29;i++)
//                    {
//                        cmbDate.addItem(z2);
//                        z2++;
//                    }
//                }
//            }
//            else
//            {
//                day30();
//            }
//        }
//        else
//        {
//            if(index >7)
//            {
//                if(index / 2 == 0)
//                {
//                    day31();
//                }
//                else
//                {
//                    day30();
//                }
//            }
//        }
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLinegraph;
    private javax.swing.JButton btnLogout;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbSelect;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration//GEN-END:variables
}
